### ISSUE TITLE
Not able to send image and file

### ISSUE THREAD

**Issue by sagarOffsec** [devlikeapro/whatsapp-http-api#13]
I have tried both WhatsApp-http-api and whatsapp-api-venom (https://github.com/diazzaid/whatsapp-api-venom)

but it's still the same. please help me to resolve the issue!

{"statusCode":501,"message":"Not Implemented"}%

Thanks!🙂

**Comment by allburov** [comment]
@sagarOffsec hi! Yep, the method doesn't have an API wrapper yet.

The project is looking for contributors or sponsors, since I no longer use the project and there is no time to add new features :(

**Comment by sagarOffsec** [comment]
Is there any other repo to which i can refer? Kindly advice please.😇

**Comment by allburov** [comment]
I think original venom is the right place, they offer HTTP API too (as paid plan tho)

**Comment by allburov** [comment]
I added a short section [for the support](https://github.com/allburov/whatsapp-http-api#support).

If you're interested in sending images you can [support project once](https://boosty.to/allburov/posts/e7db2841-5b53-4e5e-bb37-e0fdcbab8d2b) and I'll focus on in specific task before on the next release!

**Comment by allburov** [comment]
Sending files, images, and voices are available in **WAHA Plus** version now https://waha.devlike.pro/docs/how-to/send-messages/

Please note that it works only with Webjs engine, not old Venom one - the payload might be changed https://waha.devlike.pro/docs/how-to/engines/
