### ISSUE TITLE
lost session 

### ISSUE THREAD

**Issue by FelipeVeiga** [devlikeapro/whatsapp-http-api#15]
hello dear,
everthing works.
but when i resetart the server it lose the session.
i check the /app/tokens and its empty.

how can i keep the session ?

**Comment by Bigmacc00** [comment]
+1 experienced the same issue. The session was lost after application restart

**Comment by allburov** [comment]
Hi! When I tested it there was a bug in venom (underlying library), but may be it's gone and we should just update venom version.

If one find the solution - feel free to create a pull request!

**Comment by allburov** [comment]
Saving sessions is available in **WAHA Plus** version https://waha.devlike.pro/docs/how-to/sessions/

I'm not sure why, but sometimes Venom engine don't want to find previous session and we have to purge `.sessions` directory each time. If it repeats for you - please use default webjs engine instead https://waha.devlike.pro/docs/how-to/engines/
